title: FreeSprings Project
email: addison@freesprings.org
description: >- # this means to ignore newlines until "baseurl:"
  The FreeSprings Project was created to host _open and easily contributable_ cave maps and information, in order to supplement the caving community.
baseurl: ""
url: "https://freesprings.org"

permalink: /:categories/:title:output_ext

collections:
  caves:
    output: true

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: air
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

logo: "/assets/images/logo1.svg"
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
